<style type="text/css">
    .pdpmodal{
        width: 100%;
        height: 100%;
        position: fixed;
        top: 0;
        left: 0;
        display: none;
        z-index: 99999;
    }
    .pdpmodal-back{
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background: #000;
        background: rgba(0, 0, 0, 0.6);
    }
    .pdpmodal-modal{
        width: 930px;
        height: 500px;
        top: 50%;
        left: 50%;
        position: relative;
        margin-top: -265px;
        margin-left: -480px;
        background: #fff;
        padding: 15px;
    }
    .pdpmodal-modal div{
        overflow: hidden;
        overflow-y: auto;
        padding-right: 10px;
        height: 100%;
    }
    .pdpmodal-modal a.close_modal{
       position: absolute;
        right: -13px;
        top: -13px;
        font-size: 20px;
        text-align: center;
        border-radius: 30px;
        text-decoration: none;
        color: #333;
        font-weight: bold;
        width: 30px;
        height: 25px;
        background: #FFB500;
        padding-top: 5px;
        box-shadow: 0px 0px 4px #333;
    }
</style>
<div class="pdpmodal">
    <div class="pdpmodal-back"></div>
    <div class="pdpmodal-modal">
        <a class="close_modal" href="#">x</a>
        <div>
            <h2>Políticas de privacidad <span>Kkatoo - Social Dialing</span></h2>
            <p><strong><u>AVISO DE  PRIVACIDAD PORTAL KKATOO (Versión 1.0. Fecha entrada en vigor: </u></strong><strong><u>6/03/2014</u></strong><strong><u>)</u></strong></p>
<p>A través del presente Aviso de Privacidad (en lo que  sigue, <em>«Política de Privacidad»</em>), se  regula la política de privacidad del Portal de Internet <em>«http://kka.to/»</em> (en adelante, <em>«</em>el  Portal<em>»</em>), bajo la titularidad de la Fonomarketing  SAS, -en  adelante, la <em>«EMPRESA»</em>-, con  domicilio social en Medellín- Antioquia- Colombia (calle 39 # 64-14)  y  con NIT 900.519.795-0, y que pone a disposición de los/las usuarios/as del  Portal (en lo que sigue, <em>&ldquo;el usuario&rdquo;</em> o <em>&ldquo;los usuarios&rdquo;</em>). El teléfono y la  dirección de correo electrónico de contacto de la EMPRESA son, respectivamente,  las que siguen 444-12-63 <a href="mailto:info@kkatoo.com">info@kkatoo.com</a>. </p>
<p><strong>1. ANTES DE  REGISTRARSE O NAVEGAR POR NUESTRO PORTAL, CONOZCA NUESTRA POLÍTICA DE  PRIVACIDAD:</strong></p>
<p>Es nuestro deber garantizar a los usuarios del Portal el  pleno y efectivo ejercicio del derecho de hábeas data o de protección de datos  personales, e informarles debidamente sobre la finalidad de la recolección de  los datos personales, así como de los derechos que les asisten de una forma  transparente, sencilla y clara (artículo 17 por relación con el artículo 4 de  la Ley Estatutaria nº 1581, de 17 de Octubre de 2012, por la cual se dictan  Disposiciones generales para la Protección de Datos Personales (en adelante,  Ley General de Protección de Datos Personales (LGPD)). </p>
<p>Por este motivo, le recomendamos que, antes de navegar o  registrarse en el Portal, lea atentamente nuestra política de privacidad,  puesto que tal navegación y registro en el Portal implicará su autorización al  tratamiento de sus datos personales conforme la información y fines indicados  en éste y en sus específicas políticas de tratamiento de datos personales.</p>
<p>En aplicación de los principios de finalidad y libertad  contenidos en el artículo 4 de la LGPD, la recolección o recogida de datos  personales por la EMPRESA se limitará que aquellos que resulten necesarios y  pertinentes para la finalidad o fines de tratamiento descritos por la misma a  través de este Aviso y del propio Portal.</p>
<p>Sin perjuicio de los derechos de los titulares de los  datos personales, la EMPRESA cancelará o suprimirá de oficio información  personal de sus titulares cuando ya no sea adecuado, pertinente o necesario su  tratamiento, de acuerdo con los fines que justificaron su recolección y  posterior tratamiento, si bien podrán ser conservados por la EMPRESA cuando así  se requiera para el cumplimiento de una obligación legal o contractual  (artículo 11 del Decreto nº 1377 de 27 de Junio de 2013 que desarrolla la Ley  Estatutaria nº 1581, de 17 de Octubre de 2012 (en lo que sigue, Decreto nº 1377  de 2013)).</p>
<p>Se destaca que gran parte de nuestros usuarios y clientes  podrán tener, a su vez, el carácter de responsables del tratamiento, según  prevé la anterior legislación, por lo que éstos deberán ser especialmente  diligentes a la hora de tratar, transmitir o comunicar datos a la EMPRESA, que  actúa en este este caso como una mera encargada del tratamiento, precisamente,  en orden a la debida prestación por ésta de los servicios requeridos por  aquellos. Por este motivo, se recuerda a estos usuarios y/o clientes la  necesidad de que igualmente conozcan y observen de forma estricta la actual  normativa reguladora del derecho de hábeas data o de protección de datos  personales, con especial atención a los derechos de los niños, niñas y  adolescentes (artículo 7 de la LGPD y el artículo 12 del Decreto nº 1377 de  2013). </p>
<p>De forma particular, según prevé el artículo 17 de la  LGPD, el usuario-responsable del tratamiento que corresponda deberá frente a la  EMPRESA (encargada del tratamiento):</p>
<ul>
  <li>Garantizar  que la información que le suministre sea veraz, completa, exacta, actualizada,  comprobable y comprensible.</li>
  <li>Actualizar la  información, comunicando de forma oportuna, todas las novedades respecto de los  datos que previamente le haya suministrado y adoptar las demás medidas  necesarias para que la información suministrada a este se mantenga actualizada; </li>
  <li>Rectificar la  información cuando sea incorrecta y comunicar lo pertinente a la EMPRESA; </li>
  <li>Suministrar,  según el caso, únicamente datos cuyo tratamiento esté previamente autorizado de  conformidad con lo previsto en la vigente normativa.</li>
  <li>Informar  cuando determinada información se encuentra en discusión por parte del titular,  una vez se haya presentado la reclamación y no haya finalizado el trámite  respectivo</li>
</ul>
<p>Específicamente, cuando la EMPRESA actúe en calidad de  encargada del tratamiento, también cumplirá de forma puntual con todas y cada  una de las obligaciones descritas en el artículo 18 de la LGPD y su normativa  de desarrollo.</p>
<p><strong>2. DEBER DE  INFORMACIÓN, FINALIDAD:</strong></p>
<p>La EMPRESA informa a los usuarios del Portal, en  cumplimiento de los artículos 4, 8 c), 11, 12, 13, 17 c) de la Ley Estatutaria  nº 1581, de 17 de Octubre de 2012, y los artículos 13 a 17 del Decreto nº 1377  de 27 de Junio de 2013, que esta entidad ostenta bases con datos personales,  asociados al correcto desarrollo y a la gestión integral del proyecto y  servicios vinculados a KKATOO al que alude este Portal de duración, en principio,  indefinidos y, en todo caso, correspondientes a los usuarios y/o interesados o  clientes que, libre y voluntariamente, deseen aportarlos a fin de permitirles  un efectivo acceso a los específicos contenidos y servicios requeridos y  dispuestos a través del Portal. </p>
<p>Salvo que específicamente se establezca lo contrario, se  considerará necesario completar todos los datos que se indiquen como  obligatorios en los diversos formularios que puedan disponerse o se dispongan a  través del Portal. En caso de no suministrar los datos estimados como  necesarios u obligatorios, la EMPRESA podrá decidir libremente no proceder al  registro del usuario, llegado el caso, o denegar el acceso a los contenidos,  servicios o actuaciones dispuestas por esta mercantil a través del Portal.</p>
<p>El usuario deberá cumplimentar los formularios que se  faciliten a través del Portal con datos verdaderos, exactos, completos y  actualizados, respondiendo de los daños y perjuicios que pudiera ocasionar a la  EMPRESA o a terceros como consecuencia de la inobservancia de tales aspectos.  Todo ello en observancia al principio de veracidad o calidad (art.4 d) de la  LGPD).</p>
<p>Por último, el usuario o titular, sus causahabientes, o  persona que legal o voluntariamente lo represente, podrá ejercitar, en  cualquier momento, su derecho a conocer, acceder, actualizar y rectificar sus  datos personales (derechos personales de los titulares) de acuerdo con lo  establecido en la LGPD y su normativa de desarrollo. Igualmente tendrá derecho  a solicitar la supresión de sus datos personales, así como a ejercitar el  derecho a la revocación de la autorización al tratamiento cuando éste no  respete los principios, derechos y demás garantías constitucional o legalmente  protegidas. </p>
<p>A estos efectos, el usuario podrá realizar, en cualquier  momento y de forma gratuita, consultas acerca de la información personal que  ostenta la EMPRESA en sus bases de datos y que hayan sido objeto de tratamiento  por la misma (art.14 LGPD). Igualmente es posible realizar reclamos cuando  considere que la información contenida   en estas bases de datos deba ser objeto de corrección, rectificación,  actualización o supresión, o simplemente cuando adviertan el presunto  incumplimiento de cualquiera de los deberes que nos competan de conformidad con  la normativa aplicable en este ámbito (art.15 LGPD).</p>
<p><strong><u>Consultas:</u></strong> Con carácter  general, el usuario o titular (o sus causahabientes o representantes legales o  voluntarios debidamente acreditados) tiene derecho a consultar u a acceder a la  información personal que se encuentre en las bases de datos bajo el control y  titularidad de la EMPRESA. Este derecho se atenderá por la EMPRESA en el plazo  máximo de diez (10) días hábiles contados a partir de la recepción efectiva de  la consulta. Cuando no fuera posible atender a la consulta dentro de dicho  término, se informará al interesado expresando los motivos de la demora y  señalando la fecha en que se atenderá su consulta, la cual, en ningún caso  superará, según dispone la norma aplicable, los cinco (5) días hábiles  siguientes al vencimiento del primer término.</p>
<p>El usuario titular de los datos personales o, en su caso,  sus causahabientes, representantes legales o voluntarios debidamente  acreditados a estos efectos, podrán consultar de forma gratuita tales datos:  (i) al menos una vez cada mes calendario (ii) cada vez que existan  modificaciones sustanciales de las políticas de tratamiento de la EMPRESA. </p>
<p>Para consultas cuya periodicidad sea mayor a una por cada  mes calendario, la EMPRESA podrá cobrar al titular los gastos de envío,  reproducción y, en su caso, certificación de documentos. Los costos de  reproducción no podrán ser mayores a los costos de recuperación del material  correspondiente. </p>
<p><strong><u>Reclamos:</u></strong> Con carácter  general, el usuario o titular (o sus causahabientes o representantes legales o  voluntarios debidamente acreditados), cuando consideren que la información  contenida en las bases de datos de la EMPRESA deba ser objeto de corrección,  actualización o supresión, o cuando adviertan el presunto incumplimiento de  cualquiera de los deberes contenidos en la ley, podrán presentar un reclamo ante  la EMPRESA el cual será tramitado por ésta bajo las siguientes reglas:</p>
<p>1) El reclamo se formulará mediante solicitud dirigida a  la EMPRESA, con la identificación del usuario o titular, la descripción de los  hechos que dan lugar al reclamo y la dirección, debiendo acompañar los  documentos que se quiera hacer valer. Si el reclamo resulta incompleto, se requerirá  al interesado para que, dentro de los cinco (5) días siguientes a la recepción  del reclamo, éste subsane las posibles fallas. Transcurridos dos (2) meses  desde la fecha del requerimiento, sin que el solicitante presente la  información requerida, se entenderá que éste ha desistido del reclamo.<br />
  En caso de que la EMPRESA no sea competente para  resolverlo, dará traslado a quien corresponda en un término máximo de dos (2)  días hábiles e informará de la situación al usuario, interesado o titular de  los datos.</p>
<p>2) Una vez recibido el reclamo completo, se incluirá en  la base de datos una leyenda que diga &quot;reclamo en trámite&quot; y el  motivo del mismo, en un término no mayor a dos (2) días hábiles. Dicha leyenda  se mantendrá hasta que el reclamo sea decidido.</p>
<p>3) El término máximo para atender el reclamo será de  quince (15) días hábiles contados a partir del día siguiente a la fecha de su  recibo. Cuando no fuere posible atender el reclamo dentro de dicho término, se  informará al interesado acerca de los motivos de la demora y la fecha en que se  atenderá su reclamo, la cual en ningún caso superará los ocho (8) días hábiles  siguientes al vencimiento del primer término.</p>
<p>En todo caso, se debe tener en cuenta que la solicitud de  supresión de la información y la revocatoria de la autorización no procederán  cuando el titular tenga un deber legal o contractual de permanecer en la base  de datos.</p>
<p><strong>¿Dónde y cómo  debe dirigirse el usuario a la Empresa para formular una consulta o realizar un  reclamo ante la misma?</strong></p>
<p>Puede remitirnos su consulta, reclamo o solicitud,  acompañando a la misma aquella información o documentación descrita a nivel  normativo,  y dirigirla al Área  responsable a estos efectos en la EMPRESA, bajo la responsabilidad de D./Dña  Valeria Salazar Cañola, en calidad de titular de las funciones de protección de  datos en aquélla, a través de la dirección de correo electrónico <a href="mailto:vsalazar@kkatoo.com">vsalazar@kkatoo.com</a> para su adecuada tramitación  conforme a la legislación aplicable. Si lo desea, también puede remitir su  solicitud, consulta o reclamo por escrito a la dirección postal señalada al  inicio de este Aviso, indicando igualmente el Área y persona responsable dentro  de la EMPRESA para ejercitar las funciones de protección de datos personales según  lo descrito con anterioridad.</p>
<p>No dude en contactarnos si requiere mayor información  sobre nuestras políticas de tratamiento de datos o acerca de los procedimientos  para el ejercicio de sus derechos a través de los datos de contacto del Área y la  persona responsable en la EMPRESA en materia de protección de datos personales.  Igualmente, ponemos a su disposición los enlaces de la Superintendencia de  Comercio de Industria y Comercio (Delegatura para la Protección de los datos  Personales):<a href="http://www.sic.gov.co/es/proteccion-de-datos-personales1">http://www.sic.gov.co/es/proteccion-de-datos-personales1</a> y <a href="http://www.sic.gov.co/es/delegatura-para-la-proteccion-de-datos-personales">http://www.sic.gov.co/es/delegatura-para-la-proteccion-de-datos-personales</a>.</p>
<p><strong>3.  AUTORIZACIÓN DEL INTERESADO.</strong></p>
<p>En cumplimiento del principio de libertad previsto en el  artículo 4 de la LGPD, el tratamiento sólo podrá ejercerse por la EMPRESA con  el consentimiento previo, expreso e informado del usuario o titular de los  datos personales obtenido por cualquier medio válido a estos efectos (según lo  previsto en el artículo 7 del Decreto nº 1377 de 2013) y que pueda ser objeto  de consulta posterior. En tal sentido, el usuario o titular podrá solicitar  prueba de la autorización otorgada al responsable del tratamiento, salvo cuando  tal autorización resulte innecesaria a los efectos del tratamiento previsto  según dispone el artículo 10 de la LGPD (por ejemplo, en el caso de datos de  naturaleza pública; tratamiento para fines históricos, estadísticos o científicos;  etc).</p>
<p>La EMPRESA tampoco podrá divulgar estos datos a terceros  sin la previa autorización del usuario o titular, salvo que un mandato legal o  judicial así se lo imponga y, en este caso, releve del necesario consentimiento  previo a estos efectos. En este ámbito, y de forma especial, la EMPRESA  reconoce y asume el denominado principio de acceso y circulación restringida  previsto en el artículo 4 f) de la LGPD.</p>
<p>El registro de datos personales de los usuarios, mediante  el uso de los formularios electrónicos dispuestos a través del Portal o, en su  caso, mediante la remisión de mensajes de correo electrónico, o cualquier otra  vía o medio electrónica y/o telemática o no a la EMPRESA implica, salvo que se  indique expresamente lo contrario, el consentimiento del titular remitente al  tratamiento o manejo de los datos incluidos en los medios de comunicación  indicados, conforme las finalidades informadas e indicadas a través del Portal,  sus políticas de tratamiento y los distintos formularios de contacto o registro  dispuestos a este nivel y, en definitiva, asociadas a las finalidades de  tratamiento previstas en las bases de datos personales bajo la titularidad y  control de la EMPRESA en los que dicha información personal se incluye. Todo  ello, además, en coherencia con las comunicaciones, solicitudes, consultas,  comentarios o sugerencias planteadas por los propios usuarios y la vigente  normativa en cada momento.</p>
<p><strong>4.  TRATAMIENTO DE DATOS PERSONALES DE MENORES.</strong></p>
<p>Con carácter general, el Portal no está destinado a menores  de edad (niños, niñas y adolescentes) por lo que su acceso y uso, incluyendo  los servicios y contenidos dispuestos a través del mismo, queda prohibido a los  mismos, salvo que éstos cuenten con la autorización y consentimiento previo y  expreso de sus respectivos representantes legales y, aún así, siempre limitado  al tipo de datos personales y a los términos y condiciones descritas en los  artículos 7 de la LGPD y 12 del Decreto nº 1377 de 2013. Además, también se  deberá ostentar la capacidad legal necesaria a estos efectos. Los  representantes legales de los menores serán considerados, en todo caso, como  responsables plenos de los actos que lleven a cabo los menores a su cargo en  atención la normativa vigente. </p>
<p>Los representantes legales de los menores de edad y la  propia EMPRESA siempre decidirán u actuarán, respectivamente, atendiendo al  interés superior del menor y con absoluto respeto a sus derechos fundamentales.  Asimismo, los representantes legales de los menores otorgarán la autorización que  corresponda previo ejercicio del menor de su derecho a ser escuchado, opinión  que será valorada teniendo en cuenta la madurez, autonomía y capacidad para  entender del asunto de que se trate.</p>
<p>La EMPRESA, en estos casos, articulará los procedimientos  necesarios que garanticen que se ha comprobado de modo efectivo la edad del  menor, así como la autenticidad del consentimiento u autorización prestada en  su caso, por sus padres, tutores o representantes legales.</p>
<p><strong>5. SEGURIDAD.</strong></p>
<p>En aras a la existencia de políticas internas efectivas,  y con independencia de otros elementos mencionados en el artículo 27 del  Decreto nº 1377 de 2013, la EMPRESA ha adoptado y aplica criterios y medidas  específicos protección, tanto de índole técnica como organizativa, conservando  la información personal accedida bajo adecuadas condiciones de seguridad para  impedir su adulteración, pérdida, consulta, uso o acceso no autorizado o  fraudulento habida cuenta del estado de la tecnología, la  naturaleza de los datos registrados y los riesgos a que están expuestos, ya  provengan de la acción humana o del medio físico o natural.</p>
<p>Asimismo, la EMPRESA informará a la autoridad de  protección de datos de las posibles violaciones a los códigos de seguridad y  cuando existan riesgos en la administración de la información de los usuarios.</p>
<p>Las medidas y procedimientos que se dispongan por la  empresa en este ámbito resultarán coherentes con la normativa aplicable y las  instrucciones que, a estos efectos, pueda dirigirle la Superintendencia de  Industria y Comercio (artículo 19 del Decreto nº 1377 de 2013).</p>
<p>La EMPRESA prestará especial atención a la implementación  práctica de tales criterios, procedimientos y medidas realizando, a nivel  interno, cuantos programas de capacitación, formación u entrenamiento resulten  necesarios en relación a su equipo humano y personal.</p>
<p>No obstante, y a pesar de lo anterior, el usuario debe  ser consciente de que las medidas de seguridad o técnicas de protección en  Internet no son, en modo alguno, inexpugnables. </p>
<p><strong>6. DEBER DE  SECRETO Y CONFIDENCIALIDAD. </strong></p>
<p>La EMPRESA se compromete a cumplir con el deber de  secreto y de confidencialidad respecto a los datos personales contenidos en las  bases de datos personales bajo su responsabilidad, de acuerdo con la  legislación que, en cada momento, resulte legalmente exigible. Asimismo, cuando  actúe como encargado del tratamiento también observará de forma especial tales  deberes y principios en desarrollo o prestación de los servicios que  corresponda por cuenta de los respectivos responsables del tratamiento  (artículo 18 b) y j) de la LGPD).</p>
<p>En aplicación del principio de confidencialidad que rige  igualmente la actividad de la EMPRESA, todas las personas y personal que  intervenga en el tratamiento de sus datos personales están obligadas a  garantizar la reserva de la información personal accedida, incluso, aún después  de finalizada su posible relación jurídica con la EMPRESA, o de la terminación  de las específicas labores de tratamiento que les pudieran competer en este  ámbito (artículo 4 h) de la LGPG).</p>
<p><strong>7. INFORMACIÓN  SOBRE COOKIES Y TÉCNICAS &ldquo;SPAMMING&rdquo;.</strong></p>
<p>LA EMPRESA podrá utilizar cookies cuando el usuario  navegue por los sitios y páginas web del Portal. Éstas, únicamente, se  asociarán con el navegador de un ordenador/terminal/dispositivo determinado (un  usuario anónimo), y no proporcionan por sí el nombre y apellidos del mismo.  Gracias a las cookies resulta posible que la EMPRESA reconozca los navegadores  de los usuarios registrados para acceder a las posibles áreas y servicios  reservados exclusivamente a ellos, en su caso, resultando indispensables para  el funcionamiento de las aplicaciones de datos asociadas a los servicios de la  EMPRESA de tal forma que, su no aceptación, implicaría la imposibilidad de la  correcta prestación de los servicios dispuestos en este ámbito. La EMPRESA no  servirá cookies con fines publicitarios/promocionales y no realizará publicidad  comportamental basada en la instalación de cookies de rastreo en el navegador  de los usuarios y la recolección de información personal útil a fin de  segmentar sus perfiles, gustos o intereses específicos. </p>
<p>El usuario tiene la posibilidad de configurar su  navegador, si éste no hubiera sido configurado en este sentido con carácter  previo, para ser avisado en pantalla de la recepción de cookies y para impedir  la instalación de cookies en su disco duro. Por todo ello, le recomendamos que  consulte las instrucciones y manuales de su navegador para ampliar esta  información y, en su caso, bloquear esta posibilidad. </p>
<p>Asimismo, le informamos que, aunque medie consentimiento  del usuario en este ámbito, siempre que el usuario lo desee, podrá explorar su  disco duro siguiendo el manual de instrucciones y ayuda de su sistema operativo  (normalmente, en sistemas operativos Windows deberá consultar la carpeta «C» o  la unidad de disco correspondiente/windows/cookies o windows/archivos  temporales de internet) para conocer con mayor detalle cada servidor desde  donde se envían las cookies y, en su caso, proceder a su borrado.</p>
<p>En todo caso, cuando sea técnicamente posible y eficaz,  el consentimiento del destinatario para aceptar el tratamiento de datos podrá  facilitarse por la EMPRESA mediante el uso de los parámetros adecuados del  navegador o de otras aplicaciones. Para que este procedimiento sea válido, el  usuario deberá proceder a la configuración de estos parámetros, permitiendo la  entrada de cookies, en el momento de la instalación o actualización del  navegador mediante una acción expresa a tal efecto. </p>
<p>Ahora bien, lo anterior no impedirá el posible  almacenamiento o acceso de índole técnica al solo fin de efectuar la  transmisión de una comunicación por una red de comunicaciones electrónicas.  Tampoco impedirá, en la medida que resulte estrictamente necesario, el posible  almacenamiento o acceso para la prestación de un servicio de la sociedad de la  información expresamente solicitado por el destinatario. </p>
<p>La EMPRESA no utiliza técnicas de &quot;spamming&quot; y,  únicamente, tratará los datos que el usuario transmita, en los términos y  condiciones consentidas por los propios usuarios o permitidas por la ley, a  través de los formularios o mecanismos electrónicos habilitados en este sitio  web, mensajes de correo electrónico, u cualesquiera otras comunicaciones, ya  tengan o no carácter electrónico y/o telemático. </p>
<p><strong>8. TRANSFERENCIAS  Y TRANSMISIÓN INTERNACIONALES DE DATOS PERSONALES.</strong></p>
<p>Conforme define el artículo 3 del Decreto nº 1377 de 2013  la transferencia de datos tiene lugar cuando el responsable y/o encargado del tratamiento  de datos personales, ubicado en Colombia, envía la información o los datos  personales a un receptor, que a su vez es responsable del tratamiento y se  encuentra dentro o fuera del país. </p>
<p>En cambio, nos encontramos ante una transmisión de datos  personales cuando la comunicación de los mismos dentro o fuera del territorio  de la República de Colombia tenga por objeto la realización de un tratamiento  por el encargado por cuenta del responsable.</p>
<p>Las transferencias internacionales de datos personales  observarán lo previsto en el artículo 26 de la Ley 1581 de 2012, por lo que la  EMPRESA se compromete a respetar la prohibición de transferir datos personales  de cualquier tipo a países que no proporcionen niveles adecuados de protección  de datos, es decir, a países que no cumplan con los estándares fijados por la  Superintendencia de Industria y Comercio sobre la materia.<strong>  </strong>En todo caso, esta prohibición  no regirá, entre otros, en los siguientes casos especiales: </p>
<ul>
  <li>Información  respecto de la cual el usuario o titular haya otorgado su autorización expresa  e inequívoca para la transferencia;</li>
  <li>Transferencias  bancarias o bursátiles, conforme a la legislación que les resulte aplicable;</li>
  <li>Transferencias  acordadas en el marco de tratados internacionales en los cuales la República de  Colombia sea parte, con fundamento en el principio de reciprocidad;</li>
  <li>Transferencias  necesarias para la ejecución de un contrato entre el titular y la EMPRESA, o  para la ejecución de medidas precontractuales siempre y cuando se cuente con la  autorización del titular; </li>
  <li>Transferencias  legalmente exigidas para la salvaguardia del interés público, o para el  reconocimiento, ejercicio o defensa de un derecho en un proceso judicial. </li>
</ul>
<p>Con independencia de lo anterior, las transmisiones  internacionales de datos personales que se efectúen entre la EMPRESA y un  encargado para permitir que éste realice el tratamiento por cuenta de aquella,  no requerirán ser informadas al usuario o titular ni contar con su  consentimiento cuando exista un contrato en los términos del artículo 25 del  Decreto nº 1377 de 2013. </p>
<p>Conforme lo anterior, y al objeto de garantizar la máxima protección legal posible, con  carácter general, los servidores donde se aloje la información personal bajo su  responsabilidad de la EMPRESA se encontrarán, bien en la República de Colombia,  bien en servidores situados en países cuyo nivel de protección se considere  equiparable o suficientes por la Superintendencia de Industria y Comercio. Ahora bien, si concurre  alguna de las condiciones que eximen de la prohibición que impide la  transferencia de datos personales a países que no proporcionen niveles  adecuados de protección de datos ésta se podrá realizar por la EMPRESA  cumplimiento las condiciones y garantías legalmente dispuestas en este ámbito. </p>
<p><strong>9. MODIFICACIÓN  POLÍTICA DE PRIVACIDAD.</strong></p>
<p>LA EMPRESA se reserva el derecho de modificar la Política  de Privacidad, para adaptarla, con carácter básico, a futuras novedades  normativas o jurisprudenciales que resulten de aplicación. </p>
<p>En caso de haber cambios sustanciales en el contenido de  las políticas del tratamiento de datos personales de la EMPRESA, referidos a la  identificación del Responsable y a la finalidad del Tratamiento de los datos  personales, los cuales puedan afectar el contenido de la autorización otorgada  por el correspondiente titular, la EMPRESA comunicará estos cambios  oportunamente al titular de manera eficiente antes de o a más tardar al momento  de implementar las nuevas políticas, debiendo obtener, además, las  autorizaciones previas precisas cuando el cambio se refiera a los fines o  finalidad del tratamiento.</p>
<p>En todo caso, le recomendamos que cada vez que acceda al  Portal, o a cualquiera de sus contenidos o servicios, lea con detalle la  presente política de privacidad. </p>
<p>Se le recuerda que, en caso de duda o controversia  relativa a nuestra política de privacidad y de protección de datos personales, puede  ponerse en contacto con nosotros dirigiéndose al Área responsable a estos  efectos en la EMPRESA, bajo la responsabilidad de D./Dña Valeria Salazar Cañola,  en calidad de titular de las funciones de protección de datos en aquélla, a  través de la dirección de correo electrónico <a href="mailto:vsalazar123@kkatoo.com">vsalazar123@kkatoo.com</a> para su  adecuada tramitación conforme a la legislación aplicable. Si lo desea, también puede  remitirla por escrito a la dirección postal señalada al inicio de este Aviso,  con expresa mención al Área y persona responsable dentro de la EMPRESA para  ejercitar las funciones de protección de datos personales según lo descrito con  anterioridad.</p>
        </div>
    </div>
</div>